version: '3.7'

services:
  graphhopper:
    container_name: graphhopper_oberfranken
    image: graphhopper:master
    volumes:
       - ./data:/data
       - ./graphhopper/config.yml:/graphhopper/config.yml
    ports:
      - "8989:8989"
    command : ["/data/oberfranken-latest.osm.pbf"]


